#+title: Lab 6: Data Scavenger Hunt
#+author:
#+date:  8 October 2024
:export:
#+latex_class: tufte-handout
#+options: toc:nil
#+latex_compiler: xelatex
#+latex_header: \usepackage[final]{microtype}
#+latex_header: \usepackage{fontspec}
#+latex_header: \setmainfont{Gentium Plus}
#+latex_header: \setmonofont[Scale=0.8]{Maple Mono NF}
#+latex_header: \renewcommand\allcapsspacing[1]{{\addfontfeature{LetterSpace=15}#1}}
#+latex_header: \renewcommand\smallcapsspacing[1]{{\addfontfeature{LetterSpace=10}#1}}
#+latex_header: \usepackage{enumitem}
#+latex_header: \setlist{nosep}
#+property: header-args :eval no-export
:end:

* Instructions
1. Create a folder inside your DS-1043 Git repository named ``datasets''. Download ``counties.json'' from the repository at [[https://github.com/evangambit/JsonOfCounties]], place it in your ``datasets'' folder and commit it to your repository. (You do not need to clone this repository, just download that one file.)
2. Write a python program (~lab6.py~) that creates a report answering the questions posed in this lab assignment using the data found in your ~"datasets/counties.json"~. The report should be a text file named ``report.md'' formatted in Markdown (see [[https://www.markdownguide.org/basic-syntax/]] for the basic syntax for Markdown). Do *not* commit the report, just the program and dataset used to generate the report. You are expected to document your code and create tests for any functions you create to complete this assignment in an appropriately named file.
3. Revise your ~lab4.py~ to raise appropriate exceptions when given inappropriate inputs and adjust your tests to check for exceptions instead of ~None~.
4. Submit the url of your repository and the id for the commit you wish to be graded on Harvey. It should be a commit in which changes from both (2) and (3) on this list are present.

* Find the county where...
For the following questions, find the county or counties that fit the description. Your report for this should have a top-level header containing the lab title, followed by a subsection for each county description in this exercise. The body of each subsection should contain a generated sentence of the form: "{county}, {state} is the {description}." followed by a table showing the relevant data points for that and up to four others (five total). Your code should be able to handle ties, adjusting the sentence grammar accordingly.
1. Most temperature stable (i.e. least variation between Jan, Apr, Jul, and Oct temperatures)
2. Least temperature stable
3. Fastest growing
4. Fastest declining
5. Deadliest (total deaths by homicide, suicide, and vehicle per capita)
6. Least deadly
7. Most educated (college graduates per capita)
8. Least educated
9. Most skewed female
10. Most skewed male
11. Oldest (highest percentage of the population over 65)
12. Youngest (highest percentage of the population under 20)
13. Most age diverse (lowest variance between age catagories)
15. Highest employment
16. Highest unemployment

To calculate variance, first find the average of the data, then for each data point find the difference from that point and the average. Variance is the sum of the squares of these values, divided by the number of data points.

* Errata
- You can use the ~statistics~ module, including its ~variance~ function.
- Growth and Decline should be based on the percent change over the period from 2010--2019.
- Don't worry about making /pretty/ Markdown tables, just valid ones. The syntax for tables is on the ``Extended Syntax'' page of the ~markdownguide.org~ site.
